# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_auto_20160517_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='libitem',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 5, 25)),
        ),
    ]
