# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_auto_20160525_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libitem',
            name='overdue',
        ),
        migrations.AlterField(
            model_name='libitem',
            name='date_acquired',
            field=models.DateField(default=datetime.date(2016, 6, 17)),
        ),
    ]
