# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0006_auto_20160629_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libitem',
            name='pubyr',
        ),
    ]
