# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import libapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_remove_libitem_pubyr'),
    ]

    operations = [
        migrations.AddField(
            model_name='libitem',
            name='pubyr',
            field=models.IntegerField(default=2013, validators=[libapp.models.validate_yr]),
        ),
    ]
