# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0008_libitem_pubyr'),
    ]

    operations = [
        migrations.AddField(
            model_name='libuser',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_files/user_imgs/'),
        ),
    ]
