# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0012_auto_20160629_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libuser',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='libapp/uploaded_files/user_imgs/'),
        ),
    ]
